# Generated by Django 3.0.7 on 2020-08-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pass1', models.CharField(max_length=7)),
                ('date', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
