# Generated by Django 3.0.7 on 2020-08-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('url', models.ImageField(upload_to='')),
            ],
        ),
    ]
