# Generated by Django 3.0.7 on 2020-08-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttable',
            name='desc',
        ),
    ]
