# Generated by Django 3.0.7 on 2020-08-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0004_remove_producttable_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
