# Generated by Django 3.0.7 on 2020-08-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0005_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='desc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
