# Generated by Django 3.0.7 on 2020-07-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dt',
        ),
    ]
