# Generated by Django 3.0.7 on 2020-07-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
