# Generated by Django 3.0.7 on 2020-08-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
