# Generated by Django 3.0.7 on 2020-08-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productupload', '0003_auto_20200811_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
    ]
