# Generated by Django 3.0.7 on 2020-08-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productupload', '0004_auto_20200812_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/'),
        ),
    ]
