# Generated by Django 3.0.7 on 2020-07-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_todo_dt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='Todo_user',
        ),
    ]
