# Generated by Django 3.0.7 on 2020-08-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200801_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_user',
            name='user',
        ),
    ]
