# Generated by Django 3.0.7 on 2020-07-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsamples',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testsamples',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
