# Generated by Django 3.0.7 on 2020-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliateregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('pass1', models.CharField(max_length=20)),
                ('pass2', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sellerregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('pass1', models.CharField(max_length=20)),
                ('pass2', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
            ],
        ),
    ]
