# Generated by Django 3.0.7 on 2020-08-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsystem', '0003_auto_20200812_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateregister',
            name='email',
        ),
        migrations.RemoveField(
            model_name='affiliateregister',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='affiliateregister',
            name='pass2',
        ),
        migrations.RemoveField(
            model_name='affiliateregister',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellerregister',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sellerregister',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='sellerregister',
            name='pass2',
        ),
        migrations.RemoveField(
            model_name='sellerregister',
            name='user',
        ),
    ]
